sudo: false
language: python
python: 
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - TEST_TARGET=default
  - TEST_TARGET=coding_standards
jobs:
  exclude:
    - python: "2.7"
      env: TEST_TARGET=coding_standards
    - python: "3.5"
      env: TEST_TARGET=coding_standards

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py install
script:
  - if [[ $TEST_TARGET == 'default' ]]; then pytest --verbose tests ; fi
  - if [[ $TEST_TARGET == 'coding_standards' ]]; then flake8 --ignore=E501 windrose samples ; fi
  - if [[ $TEST_TARGET == 'coding_standards' ]]; then flake8 --ignore=E501,E402 tests ; fi

deploy:
  provider: pypi
  user: "scls"
  password:
    secure: nWeqLYO8BPyM1JSewV5nzspEUWSYhy+KaoWMToW5ExOmcgxBAcXyrLLcCttg15XeSO7nEN5UzauBj7upEZbybtbSzdiARlWlHwn4b9inL2EKpPjfJ2eBN98V669NCYn3EjG/CSXW9Z8njC8dRkvfboOTYr3JKPjDvWX4wK95l3Z3MHr5jdvbAgSp81XWbGG7D4nc1QdOFrxIB/56Dhw3spP6H8VYp8DruhjRyLWpLchQCFTM3x34QTOHi4iKCb+lA6lOcOC3VLJNQgWRpzpwAFCASAe9eDZuOPczBU9pZB5Vaz/YFbb/Q7rH7EZD73qzAkA431j3ozoylJx7yu75vu1jrFOWEML9wWg6oiZGwrZqkixN2zH6yCECYiR3sIb+bPZIsKwBWFNSvIMzOezgEDF/OLb28KEWkq6GUVBSSsVxalBjM1oQljPLLsatXK6B/LWwDdwTKrVAK70Df5NOYmoiQwClpDxHbm6nOyWj8aFNfKYWDqJuQQ5E+vA57J0rM7FeR5rT+CdDFp+dvK+eoaN1fae3c6JoUCgFDL4fws+HLnkuZ305F7CmCrJn9fl0sIB41kp4INRuNb4RrOyyrTx5Ff+oWU6KXfu4FMr4kzorHsNOtOz24awhybhMVtsT+amkli6ebA0vF+P7q2G91TwlLBd/Fjf/LdQSulx2Xv4=
  distributions: sdist bdist_wheel
  on:
    tags: true
